# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfoDisplayerDialog
                                 A QGIS plugin
 This plugin aims to showcase relevant informations about your open project
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-06
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Hamza widgets Inc.
        email                : hamza.rachidi@ensg.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# imports for the first user story 
from qgis.core import QgsProject, QgsMapLayerType, QgsWkbTypes

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'info_displayer_dialog_base.ui'))


class InfoDisplayerDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(InfoDisplayerDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)


# define the class for the first user story 
class InfoDisplayerDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(InfoDisplayerDialog, self).__init__(parent)
        self.setupUi(self)
        self.populate_point_layers()

    
    def populate_point_layers(self):
        """Populate the combo box with point layers from the current project."""
        self.listeCouchesPonctuelles.clear()  # Clear the combo box before populating because the layers may change in the project 

        # Get the current project
        project = QgsProject.instance()

        # Iterate through all layers in the project
        for couche in project.mapLayers().values():
            # Check if the layer is a vector layer and has point geometry before displaying, otherwise linear and polygon vector as well as rasters won't be displayed
            if couche.type() == QgsMapLayerType.VectorLayer and couche.geometryType() == QgsWkbTypes.PointGeometry:
                self.listeCouchesPonctuelles.addItem(couche.name())
